// Code generated by mfd-generator v0.4.5; DO NOT EDIT.

//nolint:all
//lint:file-ignore U1000 ignore unused code, it's generated
package db

import (
	"time"

	"github.com/go-pg/pg/v10"
	"github.com/go-pg/pg/v10/orm"
)

const condition = "?.? = ?"

// base filters
type applier func(query *orm.Query) (*orm.Query, error)

type search struct {
	appliers []applier
}

func (s *search) apply(query *orm.Query) {
	for _, applier := range s.appliers {
		query.Apply(applier)
	}
}

func (s *search) where(query *orm.Query, table, field string, value interface{}) {
	query.Where(condition, pg.Ident(table), pg.Ident(field), value)
}

func (s *search) WithApply(a applier) {
	if s.appliers == nil {
		s.appliers = []applier{}
	}
	s.appliers = append(s.appliers, a)
}

func (s *search) With(condition string, params ...interface{}) {
	s.WithApply(func(query *orm.Query) (*orm.Query, error) {
		return query.Where(condition, params...), nil
	})
}

// Searcher is interface for every generated filter
type Searcher interface {
	Apply(query *orm.Query) *orm.Query
	Q() applier

	With(condition string, params ...interface{})
	WithApply(a applier)
}

type UserSearch struct {
	search

	ID                 *int
	CreatedAt          *time.Time
	Login              *string
	Password           *string
	AuthKey            *string
	LastActivityAt     *time.Time
	StatusID           *int
	IDs                []int
	NotID              *int
	LoginILike         *string
	PasswordILike      *string
	AuthKeyILike       *string
	LastActivityAtFrom *time.Time
	LastActivityAtTo   *time.Time
}

func (us *UserSearch) Apply(query *orm.Query) *orm.Query {
	if us == nil {
		return query
	}
	if us.ID != nil {
		us.where(query, Tables.User.Alias, Columns.User.ID, us.ID)
	}
	if us.CreatedAt != nil {
		us.where(query, Tables.User.Alias, Columns.User.CreatedAt, us.CreatedAt)
	}
	if us.Login != nil {
		us.where(query, Tables.User.Alias, Columns.User.Login, us.Login)
	}
	if us.Password != nil {
		us.where(query, Tables.User.Alias, Columns.User.Password, us.Password)
	}
	if us.AuthKey != nil {
		us.where(query, Tables.User.Alias, Columns.User.AuthKey, us.AuthKey)
	}
	if us.LastActivityAt != nil {
		us.where(query, Tables.User.Alias, Columns.User.LastActivityAt, us.LastActivityAt)
	}
	if us.StatusID != nil {
		us.where(query, Tables.User.Alias, Columns.User.StatusID, us.StatusID)
	}
	if len(us.IDs) > 0 {
		Filter{Columns.User.ID, us.IDs, SearchTypeArray, false}.Apply(query)
	}
	if us.NotID != nil {
		Filter{Columns.User.ID, *us.NotID, SearchTypeEquals, true}.Apply(query)
	}
	if us.LoginILike != nil {
		Filter{Columns.User.Login, *us.LoginILike, SearchTypeILike, false}.Apply(query)
	}
	if us.PasswordILike != nil {
		Filter{Columns.User.Password, *us.PasswordILike, SearchTypeILike, false}.Apply(query)
	}
	if us.AuthKeyILike != nil {
		Filter{Columns.User.AuthKey, *us.AuthKeyILike, SearchTypeILike, false}.Apply(query)
	}
	if us.LastActivityAtFrom != nil {
		Filter{Columns.User.LastActivityAt, *us.LastActivityAtFrom, SearchTypeGE, false}.Apply(query)
	}
	if us.LastActivityAtTo != nil {
		Filter{Columns.User.LastActivityAt, *us.LastActivityAtTo, SearchTypeLE, false}.Apply(query)
	}

	us.apply(query)

	return query
}

func (us *UserSearch) Q() applier {
	return func(query *orm.Query) (*orm.Query, error) {
		if us == nil {
			return query, nil
		}
		return us.Apply(query), nil
	}
}

type MessageReactionSearch struct {
	search

	ID             *int
	ReactionsCount *int
	IDs            []int
}

func (mrs *MessageReactionSearch) Apply(query *orm.Query) *orm.Query {
	if mrs == nil {
		return query
	}
	if mrs.ID != nil {
		mrs.where(query, Tables.MessageReaction.Alias, Columns.MessageReaction.ID, mrs.ID)
	}
	if mrs.ReactionsCount != nil {
		mrs.where(query, Tables.MessageReaction.Alias, Columns.MessageReaction.ReactionsCount, mrs.ReactionsCount)
	}
	if len(mrs.IDs) > 0 {
		Filter{Columns.MessageReaction.ID, mrs.IDs, SearchTypeArray, false}.Apply(query)
	}

	mrs.apply(query)

	return query
}

func (mrs *MessageReactionSearch) Q() applier {
	return func(query *orm.Query) (*orm.Query, error) {
		if mrs == nil {
			return query, nil
		}
		return mrs.Apply(query), nil
	}
}
