// Code generated by mfd-generator v0.4.5; DO NOT EDIT.

//nolint:all
//lint:file-ignore U1000 ignore unused code, it's generated
package db

import (
	"time"
)

var Columns = struct {
	User struct {
		ID, CreatedAt, Login, Password, AuthKey, LastActivityAt, StatusID string
	}
	MessageReaction struct {
		ID, ReactionsCount string
	}
}{
	User: struct {
		ID, CreatedAt, Login, Password, AuthKey, LastActivityAt, StatusID string
	}{
		ID:             "userId",
		CreatedAt:      "createdAt",
		Login:          "login",
		Password:       "password",
		AuthKey:        "authKey",
		LastActivityAt: "lastActivityAt",
		StatusID:       "statusId",
	},
	MessageReaction: struct {
		ID, ReactionsCount string
	}{
		ID:             "messageId",
		ReactionsCount: "reactionsCount",
	},
}

var Tables = struct {
	User struct {
		Name, Alias string
	}
	MessageReaction struct {
		Name, Alias string
	}
}{
	User: struct {
		Name, Alias string
	}{
		Name:  "users",
		Alias: "t",
	},
	MessageReaction: struct {
		Name, Alias string
	}{
		Name:  "messageReactions",
		Alias: "t",
	},
}

type User struct {
	tableName struct{} `pg:"users,alias:t,discard_unknown_columns"`

	ID             int        `pg:"userId,pk"`
	CreatedAt      time.Time  `pg:"createdAt,use_zero"`
	Login          string     `pg:"login,use_zero"`
	Password       string     `pg:"password,use_zero"`
	AuthKey        string     `pg:"authKey,use_zero"`
	LastActivityAt *time.Time `pg:"lastActivityAt"`
	StatusID       int        `pg:"statusId,use_zero"`
}

type MessageReaction struct {
	tableName struct{} `pg:"messageReactions,alias:t,discard_unknown_columns"`

	ID             int  `pg:"messageId,pk"`
	ReactionsCount *int `pg:"reactionsCount"`
}
