// Code generated by mfd-generator v0.6.0; DO NOT EDIT.

//nolint:all
//lint:file-ignore U1000 ignore unused code, it's generated
package db

import (
	"time"
)

var Columns = struct {
	MessageReaction struct {
		ReactionsCount, MessageID, ChatID, CreatedAt string
	}
}{
	MessageReaction: struct {
		ReactionsCount, MessageID, ChatID, CreatedAt string
	}{
		ReactionsCount: "reactionsCount",
		MessageID:      "messageId",
		ChatID:         "chatId",
		CreatedAt:      "createdAt",
	},
}

var Tables = struct {
	MessageReaction struct {
		Name, Alias string
	}
}{
	MessageReaction: struct {
		Name, Alias string
	}{
		Name:  "messageReactions",
		Alias: "t",
	},
}

type MessageReaction struct {
	tableName struct{} `pg:"messageReactions,alias:t,discard_unknown_columns"`

	ReactionsCount *int      `pg:"reactionsCount"`
	MessageID      int       `pg:"messageId,pk"`
	ChatID         int64     `pg:"chatId,pk"`
	CreatedAt      time.Time `pg:"createdAt,use_zero"`
}
